version: "3.7"

services:
  app:
    build:
      context: /root/wg-ui
      dockerfile: Dockerfile
    entrypoint: "/wireguard-ui"
    privileged: true
    network_mode: "host"
    volumes:
      - /opt/wireguard-ui:/data
    environment:
      - WIREGUARD_UI_LISTEN_ADDRESS=:8080
      - WIREGUARD_UI_LOG_LEVEL=debug
      - WIREGUARD_UI_DATA_DIR=/data
      - WIREGUARD_UI_WG_ENDPOINT=vpn.ascendntnu.no:51820
      - WIREGUARD_UI_CLIENT_IP_RANGE=192.168.68.1/22
      - WIREGUARD_UI_NAT=false
      - WIREGUARD_UI_WG_DEVICE_NAME=wg1

