steps:
  - name: Build container image
    agents:
      queue: default
      os: linux
    commands:
      - buildah bud --layers -t embarkstudios/wireguard-ui:latest -f Dockerfile .
      - buildah bud --layers -t embarkstudios/wireguard-ui:debug -f Dockerfile.debug .
      - buildah push embarkstudios/wireguard-ui:latest
      - buildah push embarkstudios/wireguard-ui:debug
