steps:
  - name: Build container image
    agents:
      queue: default
      os: linux
    commands:
      - buildah bud --format=docker --layers -t embarkstudios/wireguard-ui:latest -f Dockerfile .
      - buildah bud --format=docker --layers -t embarkstudios/wireguard-ui:debug -f Dockerfile.debug .
      - buildah push --authfile /root/.dockerhub/config.json embarkstudios/wireguard-ui:latest
      - buildah push --authfile /root/.dockerhub/config.json embarkstudios/wireguard-ui:debug
